window.KNOWLEDGE_CANVAS_DATA = {
  meta: {
    id: "question-framing",
    title: "Question Framing（问题定界）",
    subtitle: "把模糊问题转换成现实可回答、证据可约束的问题",
    worldWidth: 4200,
    worldHeight: 2800,
    initialScale: 0.78
  },
  categories: {
    problem: { label: "Problem Framing（问题框定）", color: "#5fd3e7" },
    core: { label: "Question Framing Core（问题定界核心）", color: "#5b8cff" },
    measure: { label: "Measurement / Validity（测量 / 效度）", color: "#49c38a" },
    type: { label: "Question Type（问题类型）", color: "#a982ff" },
    pitfall: { label: "Pitfall（常见缺陷）", color: "#ff6b6b" },
    decision: { label: "Decision（决策）", color: "#f5a65b" },
    stop: { label: "Stop Rule（停止规则）", color: "#e8d35c" },
    meta: { label: "Meta（总节点）", color: "#8ea1bf" }
  },
  nodes: [
    {id:"root",x:1940,y:1220,category:"meta",variant:"root",title:"Question Framing（问题定界）",summary:"把模糊兴趣、直觉或观点，转化为一个现实能够回答、证据能够约束、决策能够使用的问题。",details:{quote:"好的问题不是让 AI 更容易回答，而是让现实有机会纠正我们的答案。",points:["当前需求层级已完成","能力目标：Understand → Identify → Diagnose → Transfer","应用：研究 / 学习 / 产品 / 知识口播"]}},
    {id:"observation",x:300,y:420,category:"problem",title:"Observation（观察）",summary:"对当前可观察事实或数据的描述，尽量不混入原因解释。"},
    {id:"problem",x:640,y:420,category:"problem",title:"Problem（问题情境）",summary:"现实、观察或现有认知中出现的异常、困难、缺口或冲突。"},
    {id:"interpretation",x:300,y:740,category:"problem",title:"Interpretation（解释）",summary:"对 Observation 为什么发生提出的可能说明；它可以正确，也可以错误。"},
    {id:"frame",x:640,y:740,category:"problem",variant:"group",title:"Frame（问题框定）",summary:"从多个可能解释与边界中，选择当前优先从哪个角度理解和研究 Problem。"},
    {id:"working-frame",x:980,y:740,category:"problem",title:"Working Frame（工作框定）",summary:"基于当前证据暂时选择的优先研究入口，可以被后续证据修正。"},
    {id:"frame-priority",x:980,y:420,category:"problem",title:"Frame Priority（框定优先级）",summary:"Fit + Discriminability + Decision Leverage。",details:{points:["Fit：与当前 Observation 匹配","Discriminability：能与竞争 Frame 导出不同证据预期","Decision Leverage：会改变后续决策"]}},
    {id:"confounder",x:300,y:1030,category:"problem",title:"Confounder（混杂因素）",summary:"第三因素使目标关系掺入其他因果来源。"},
    {id:"control",x:640,y:1030,category:"problem",title:"Control（控制）",summary:"通过设计或分析减少竞争解释，让目标关系更清楚。",details:{quote:"Control 不是控制越多越好，而是减少会干扰当前判断的竞争解释。"}},
    {id:"topic",x:1460,y:250,category:"core",title:"Topic（主题）",summary:"知识区域：我们正在研究哪里。"},
    {id:"question",x:1790,y:250,category:"core",variant:"group",title:"Question（研究问题）",summary:"针对 Problem 提出的明确询问：我具体不知道什么？"},
    {id:"hypothesis",x:2120,y:250,category:"core",title:"Hypothesis（假设）",summary:"对 Question 提出的、尚待证据检验的候选答案。"},
    {id:"claim",x:2450,y:250,category:"core",title:"Claim（主张）",summary:"基于当前证据，研究者愿意明确承担的陈述。"},
    {id:"construct",x:1450,y:720,category:"core",title:"Construct（构念）",summary:"真正想理解、但不能直接观察的抽象属性或能力。"},
    {id:"relation",x:1760,y:720,category:"core",title:"Relation（关系）",summary:"问题究竟在问描述、比较、关联、因果、机制、预测还是决策。"},
    {id:"scope",x:2070,y:720,category:"core",title:"Scope（范围）",summary:"规定适用于谁、什么时间、什么情境或边界条件。"},
    {id:"operationalization",x:2380,y:720,category:"core",title:"Operationalization（操作化）",summary:"把抽象构念转换成可观察、可测量或可操纵的规则。"},
    {id:"evidence-condition",x:2690,y:720,category:"core",variant:"group",title:"Evidence Condition（证据条件）",summary:"说明什么观察、数据或结果会支持、削弱、区分或改变当前答案。"},
    {id:"fast-chain",x:1915,y:930,category:"core",title:"快速诊断链",summary:"Purpose → Construct → Relation → Scope → Operationalization → Evidence Condition → Stop",details:{quote:"不是每次机械执行完整链路，只检查会改变当前任务的部分。"}},
    {id:"underrepresentation",x:3060,y:350,category:"measure",title:"Construct Underrepresentation（构念覆盖不足）",summary:"测量只覆盖目标构念的一小部分，却把结果解释为整个构念。",details:{quote:"测少了"}},
    {id:"irrelevant",x:3400,y:350,category:"measure",title:"Construct-Irrelevant Variance（构念无关变异）",summary:"测量混入目标构念之外的系统影响。",details:{quote:"测杂了"}},
    {id:"convergent",x:3060,y:650,category:"measure",title:"Convergent Evidence（聚合证据）",summary:"多个不同测量若测同一构念，应在理论预期下表现一定一致性。"},
    {id:"discriminant",x:3400,y:650,category:"measure",title:"Discriminant Evidence（区分证据）",summary:"目标构念的测量应能与相近但不同的构念区分开。"},
    {id:"reliability",x:3060,y:960,category:"measure",title:"Reliability（信度）",summary:"目标状态不变时，重复测量结果保持一致的程度。",details:{quote:"核心问题：稳不稳？"}},
    {id:"validity",x:3400,y:960,category:"measure",title:"Validity（效度）",summary:"证据是否支持我们根据测量结果作出的解释和用途。",details:{quote:"高信度不保证高效度。"}},
    {id:"random-error",x:3060,y:1260,category:"measure",title:"Random Error（随机误差）",summary:"误差方向与大小不稳定，主要损害一致性与精度。"},
    {id:"systematic-error",x:3400,y:1260,category:"measure",title:"Systematic Error（系统误差）",summary:"误差具有稳定方向或结构，主要损害解释有效性。"},
    {id:"descriptive",x:640,y:1550,category:"type",title:"Descriptive（描述）",summary:"现实是什么样？看分布、频率、比例、状态。"},
    {id:"comparative",x:980,y:1550,category:"type",title:"Comparative（比较）",summary:"A 与 B 是否不同？比较可以叠加描述或因果。"},
    {id:"association",x:1320,y:1550,category:"type",title:"Association（关联）",summary:"X 与 Y 是否共同变化？关联不等于因果。"},
    {id:"causal",x:1660,y:1550,category:"type",title:"Causal（因果）",summary:"改变 X 是否导致 Y 改变？需要处理竞争解释。"},
    {id:"mechanism",x:2000,y:1550,category:"type",title:"Mechanism（机制）",summary:"X 通过什么中间过程影响 Y？"},
    {id:"prediction",x:2340,y:1550,category:"type",title:"Prediction（预测）",summary:"未知 / 未来 Y 会是什么？预测准不等于知道原因。"},
    {id:"decision-q",x:2680,y:1550,category:"type",title:"Decision（决策问题）",summary:"在目标与约束下应该采取什么行动？"},
    {id:"mediator",x:1840,y:1810,category:"type",title:"Mediator（中介变量）",summary:"位于 X→Y 因果路径内部，承接作用。"},
    {id:"moderator",x:2180,y:1810,category:"type",title:"Moderator（调节变量）",summary:"改变 X→Y 关系的强弱、方向或形式。"},
    {id:"objective",x:2840,y:1840,category:"decision",title:"Objective（目标）",summary:"规定要优化什么结果。"},
    {id:"constraint",x:3170,y:1840,category:"decision",title:"Constraint（约束）",summary:"可选方案必须满足的边界条件。"},
    {id:"means",x:3500,y:1840,category:"decision",title:"Means（手段）",summary:"为实现目标而采取的行动、策略或路径。"},
    {id:"decision-info",x:3170,y:2110,category:"decision",title:"Decision-Relevant Information（决策相关信息）",summary:"一旦其取值变化，就可能改变行动排序或最终选择。"},
    {id:"ambiguity",x:420,y:2090,category:"pitfall",title:"Ambiguity（歧义）",summary:"关键词允许多个实质不同解释，并导向不同测量、证据或答案。"},
    {id:"smuggled",x:750,y:2090,category:"pitfall",title:"Smuggled Assumption（偷带前提）",summary:"把尚未得到支持的关键命题预先当作真的。"},
    {id:"leading",x:1080,y:2090,category:"pitfall",title:"Leading Question（诱导性问题）",summary:"通过措辞、价值暗示或身份标签把回答推向特定方向。"},
    {id:"scope-drift",x:1410,y:2090,category:"pitfall",title:"Scope Drift（范围漂移）",summary:"证据范围有限，但结论阶段改变或扩大适用范围。"},
    {id:"untestable",x:1740,y:2090,category:"pitfall",title:"Untestability（不可检验性）",summary:"缺少能让现实结果明显支持、削弱或反驳命题的证据条件。"},
    {id:"self-sealing",x:2070,y:2090,category:"pitfall",title:"Self-Sealing Definition（自我封闭定义）",summary:"遇到不利案例就修改关键定义，把反例排除。"},
    {id:"overbreadth",x:2400,y:2090,category:"pitfall",title:"Overbreadth（问题过宽）",summary:"跨越太多人群、情境、变量或时间尺度，统一答案会掩盖差异。"},
    {id:"overloaded",x:2730,y:2090,category:"pitfall",title:"Overloaded Question（过载问题）",summary:"一个问题同时捆绑多个可独立回答的未知。"},
    {id:"minimum",x:1590,y:2470,category:"stop",variant:"group",title:"Minimum Sufficient Framing（最小充分定界）",summary:"继续增加精度已不太可能改变答案、证据、决策或双方理解时，就停止。",details:{quote:"问题不是越细越好，而是细到足以支撑当前目的。",points:["Answer：会不会改变答案？","Evidence：会不会改变证据选择？","Decision：会不会改变行动排序？","Interpretation：不拆会不会造成实质误解？","Cost：进一步拆解的收益是否低于沟通与认知成本？"]}},
    {id:"context",x:1970,y:2470,category:"stop",title:"Context-sensitive Precision（情境化精度）",summary:"闲聊、研究、高风险决策、专家沟通需要不同程度的定界精度。"},
    {id:"shared-context",x:2350,y:2470,category:"stop",title:"Shared Context（共享上下文）",summary:"共享背景越丰富，同样精度所需显式表达的信息越少。"}
  ],
  edges: [
    {from:"observation",to:"problem",label:"reveals",strong:true},
    {from:"observation",to:"interpretation",label:"may prompt"},
    {from:"interpretation",to:"frame",label:"feeds"},
    {from:"problem",to:"frame",label:"framed as",strong:true},
    {from:"frame",to:"working-frame",label:"prioritize"},
    {from:"frame-priority",to:"working-frame",label:"selects"},
    {from:"confounder",to:"control",label:"handled by"},
    {from:"control",to:"frame",label:"improves testability"},
    {from:"topic",to:"question",label:"narrows to"},
    {from:"problem",to:"question",label:"generates",strong:true},
    {from:"question",to:"hypothesis",label:"candidate answer"},
    {from:"hypothesis",to:"claim",label:"after evidence"},
    {from:"question",to:"construct",label:"contains"},
    {from:"question",to:"relation",label:"contains"},
    {from:"question",to:"scope",label:"contains"},
    {from:"construct",to:"operationalization",label:"made observable by"},
    {from:"question",to:"evidence-condition",label:"must admit"},
    {from:"construct",to:"root",label:"part of"},
    {from:"relation",to:"root",label:"part of"},
    {from:"scope",to:"root",label:"part of"},
    {from:"operationalization",to:"root",label:"part of"},
    {from:"evidence-condition",to:"root",label:"part of"},
    {from:"fast-chain",to:"root",label:"diagnoses"},
    {from:"operationalization",to:"underrepresentation",label:"risk"},
    {from:"operationalization",to:"irrelevant",label:"risk"},
    {from:"validity",to:"underrepresentation",label:"threatened by"},
    {from:"validity",to:"irrelevant",label:"threatened by"},
    {from:"convergent",to:"validity",label:"supports"},
    {from:"discriminant",to:"validity",label:"supports"},
    {from:"reliability",to:"validity",label:"not equal"},
    {from:"random-error",to:"reliability",label:"harms"},
    {from:"systematic-error",to:"validity",label:"harms"},
    {from:"relation",to:"descriptive",label:"type"},
    {from:"relation",to:"comparative",label:"type"},
    {from:"relation",to:"association",label:"type"},
    {from:"relation",to:"causal",label:"type"},
    {from:"relation",to:"mechanism",label:"type"},
    {from:"relation",to:"prediction",label:"type"},
    {from:"relation",to:"decision-q",label:"type"},
    {from:"association",to:"causal",label:"≠",strong:true},
    {from:"causal",to:"mechanism",label:"≠",strong:true},
    {from:"mechanism",to:"mediator",label:"contains"},
    {from:"causal",to:"moderator",label:"conditioned by"},
    {from:"decision-q",to:"objective",label:"requires"},
    {from:"decision-q",to:"constraint",label:"requires"},
    {from:"decision-q",to:"means",label:"compares"},
    {from:"decision-info",to:"decision-q",label:"changes ranking"},
    {from:"ambiguity",to:"construct",label:"confuses"},
    {from:"smuggled",to:"question",label:"distorts"},
    {from:"leading",to:"question",label:"biases"},
    {from:"scope-drift",to:"scope",label:"violates"},
    {from:"untestable",to:"evidence-condition",label:"lacks"},
    {from:"self-sealing",to:"untestable",label:"maintains"},
    {from:"overbreadth",to:"scope",label:"too wide"},
    {from:"overloaded",to:"question",label:"packs many unknowns"},
    {from:"root",to:"minimum",label:"stops at",strong:true},
    {from:"minimum",to:"context",label:"depends on"},
    {from:"context",to:"shared-context",label:"modulated by"}
  ]
};
